const additionalRating = [
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110','RATE_NAME' : '50000','RATE' : 12,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110','RATE_NAME' : '100000','RATE' : 19,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110','RATE_NAME' : '200000','RATE' : 25,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110','RATE_NAME' : '300000','RATE' : 28,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110','RATE_NAME' : '400000','RATE' : 29,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110','RATE_NAME' : '500000','RATE' : 30,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110E','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110E','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110E','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110E','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110E','RATE_NAME' : '50000','RATE' : 12,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110E','RATE_NAME' : '100000','RATE' : 19,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110E','RATE_NAME' : '200000','RATE' : 25,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110E','RATE_NAME' : '300000','RATE' : 28,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110E','RATE_NAME' : '400000','RATE' : 29,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110E','RATE_NAME' : '500000','RATE' : 30,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '110E','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120','RATE_NAME' : '50000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120','RATE_NAME' : '100000','RATE' : 90,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120','RATE_NAME' : '200000','RATE' : 110,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120','RATE_NAME' : '300000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120','RATE_NAME' : '400000','RATE' : 130,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120','RATE_NAME' : '500000','RATE' : 135,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120E','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120E','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120E','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120E','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120E','RATE_NAME' : '50000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120E','RATE_NAME' : '100000','RATE' : 90,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120E','RATE_NAME' : '200000','RATE' : 110,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120E','RATE_NAME' : '300000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120E','RATE_NAME' : '400000','RATE' : 130,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120E','RATE_NAME' : '500000','RATE' : 135,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '120E','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210','RATE_NAME' : '50000','RATE' : 30,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210','RATE_NAME' : '100000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210','RATE_NAME' : '200000','RATE' : 70,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210','RATE_NAME' : '300000','RATE' : 85,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210','RATE_NAME' : '400000','RATE' : 100,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210','RATE_NAME' : '500000','RATE' : 105,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210E','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210E','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210E','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210E','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210E','RATE_NAME' : '50000','RATE' : 30,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210E','RATE_NAME' : '100000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210E','RATE_NAME' : '200000','RATE' : 70,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210E','RATE_NAME' : '300000','RATE' : 85,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210E','RATE_NAME' : '400000','RATE' : 100,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210E','RATE_NAME' : '500000','RATE' : 105,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '210E','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220','RATE_NAME' : '50000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220','RATE_NAME' : '100000','RATE' : 90,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220','RATE_NAME' : '200000','RATE' : 110,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220','RATE_NAME' : '300000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220','RATE_NAME' : '400000','RATE' : 130,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220','RATE_NAME' : '500000','RATE' : 135,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220E','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220E','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220E','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220E','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220E','RATE_NAME' : '50000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220E','RATE_NAME' : '100000','RATE' : 90,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220E','RATE_NAME' : '200000','RATE' : 110,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220E','RATE_NAME' : '300000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220E','RATE_NAME' : '400000','RATE' : 130,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220E','RATE_NAME' : '500000','RATE' : 135,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '220E','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230','RATE_NAME' : '50000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230','RATE_NAME' : '100000','RATE' : 90,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230','RATE_NAME' : '200000','RATE' : 110,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230','RATE_NAME' : '300000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230','RATE_NAME' : '400000','RATE' : 130,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230','RATE_NAME' : '500000','RATE' : 135,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230E','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230E','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230E','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230E','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230E','RATE_NAME' : '50000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230E','RATE_NAME' : '100000','RATE' : 90,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230E','RATE_NAME' : '200000','RATE' : 110,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230E','RATE_NAME' : '300000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230E','RATE_NAME' : '400000','RATE' : 130,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230E','RATE_NAME' : '500000','RATE' : 135,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '230E','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320','RATE_NAME' : '50000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320','RATE_NAME' : '100000','RATE' : 90,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320','RATE_NAME' : '200000','RATE' : 110,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320','RATE_NAME' : '300000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320','RATE_NAME' : '400000','RATE' : 130,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320','RATE_NAME' : '500000','RATE' : 135,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320E','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320E','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320E','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320E','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320E','RATE_NAME' : '50000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320E','RATE_NAME' : '100000','RATE' : 90,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320E','RATE_NAME' : '200000','RATE' : 110,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320E','RATE_NAME' : '300000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320E','RATE_NAME' : '400000','RATE' : 130,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320E','RATE_NAME' : '500000','RATE' : 135,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '320E','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327','RATE_NAME' : '50000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327','RATE_NAME' : '100000','RATE' : 90,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327','RATE_NAME' : '200000','RATE' : 110,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327','RATE_NAME' : '300000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327','RATE_NAME' : '400000','RATE' : 130,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327','RATE_NAME' : '500000','RATE' : 135,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327E','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327E','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327E','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327E','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327E','RATE_NAME' : '50000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327E','RATE_NAME' : '100000','RATE' : 90,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327E','RATE_NAME' : '200000','RATE' : 110,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327E','RATE_NAME' : '300000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327E','RATE_NAME' : '400000','RATE' : 130,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327E','RATE_NAME' : '500000','RATE' : 135,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '327E','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340','RATE_NAME' : '50000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340','RATE_NAME' : '100000','RATE' : 90,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340','RATE_NAME' : '200000','RATE' : 110,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340','RATE_NAME' : '300000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340','RATE_NAME' : '400000','RATE' : 130,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340','RATE_NAME' : '500000','RATE' : 135,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340E','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340E','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340E','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340E','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340E','RATE_NAME' : '50000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340E','RATE_NAME' : '100000','RATE' : 90,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340E','RATE_NAME' : '200000','RATE' : 110,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340E','RATE_NAME' : '300000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340E','RATE_NAME' : '400000','RATE' : 130,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340E','RATE_NAME' : '500000','RATE' : 135,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '340E','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347','RATE_NAME' : '50000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347','RATE_NAME' : '100000','RATE' : 90,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347','RATE_NAME' : '200000','RATE' : 110,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347','RATE_NAME' : '300000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347','RATE_NAME' : '400000','RATE' : 130,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347','RATE_NAME' : '500000','RATE' : 135,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347E','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347E','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347E','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347E','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347E','RATE_NAME' : '50000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347E','RATE_NAME' : '100000','RATE' : 90,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347E','RATE_NAME' : '200000','RATE' : 110,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347E','RATE_NAME' : '300000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347E','RATE_NAME' : '400000','RATE' : 130,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347E','RATE_NAME' : '500000','RATE' : 135,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '347E','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420','RATE_NAME' : '50000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420','RATE_NAME' : '100000','RATE' : 90,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420','RATE_NAME' : '200000','RATE' : 110,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420','RATE_NAME' : '300000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420','RATE_NAME' : '400000','RATE' : 130,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420','RATE_NAME' : '500000','RATE' : 135,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420E','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420E','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420E','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420E','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420E','RATE_NAME' : '50000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420E','RATE_NAME' : '100000','RATE' : 90,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420E','RATE_NAME' : '200000','RATE' : 110,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420E','RATE_NAME' : '300000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420E','RATE_NAME' : '400000','RATE' : 130,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420E','RATE_NAME' : '500000','RATE' : 135,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '420E','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610','RATE_NAME' : '50000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610','RATE_NAME' : '100000','RATE' : 170,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610','RATE_NAME' : '200000','RATE' : 210,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610','RATE_NAME' : '300000','RATE' : 240,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610','RATE_NAME' : '400000','RATE' : 260,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610','RATE_NAME' : '500000','RATE' : 270,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620','RATE_NAME' : '50000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620','RATE_NAME' : '100000','RATE' : 170,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620','RATE_NAME' : '200000','RATE' : 210,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620','RATE_NAME' : '300000','RATE' : 240,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620','RATE_NAME' : '400000','RATE' : 260,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620','RATE_NAME' : '500000','RATE' : 270,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630','RATE_NAME' : '50000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630','RATE_NAME' : '100000','RATE' : 170,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630','RATE_NAME' : '200000','RATE' : 210,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630','RATE_NAME' : '300000','RATE' : 240,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630','RATE_NAME' : '400000','RATE' : 260,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630','RATE_NAME' : '500000','RATE' : 270,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610E','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610E','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610E','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610E','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610E','RATE_NAME' : '50000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610E','RATE_NAME' : '100000','RATE' : 170,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610E','RATE_NAME' : '200000','RATE' : 210,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610E','RATE_NAME' : '300000','RATE' : 240,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610E','RATE_NAME' : '400000','RATE' : 260,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610E','RATE_NAME' : '500000','RATE' : 270,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '610E','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620E','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620E','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620E','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620E','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620E','RATE_NAME' : '50000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620E','RATE_NAME' : '100000','RATE' : 170,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620E','RATE_NAME' : '200000','RATE' : 210,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620E','RATE_NAME' : '300000','RATE' : 240,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620E','RATE_NAME' : '400000','RATE' : 260,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620E','RATE_NAME' : '500000','RATE' : 270,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '620E','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630E','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630E','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630E','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630E','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630E','RATE_NAME' : '50000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630E','RATE_NAME' : '100000','RATE' : 170,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630E','RATE_NAME' : '200000','RATE' : 210,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630E','RATE_NAME' : '300000','RATE' : 240,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630E','RATE_NAME' : '400000','RATE' : 260,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630E','RATE_NAME' : '500000','RATE' : 270,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '630E','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730','RATE_NAME' : '50000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730','RATE_NAME' : '100000','RATE' : 90,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730','RATE_NAME' : '200000','RATE' : 110,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730','RATE_NAME' : '300000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730','RATE_NAME' : '400000','RATE' : 130,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730','RATE_NAME' : '500000','RATE' : 135,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730E','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730E','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730E','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730E','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730E','RATE_NAME' : '50000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730E','RATE_NAME' : '100000','RATE' : 90,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730E','RATE_NAME' : '200000','RATE' : 110,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730E','RATE_NAME' : '300000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730E','RATE_NAME' : '400000','RATE' : 130,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730E','RATE_NAME' : '500000','RATE' : 135,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '730E','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801','RATE_NAME' : '50000','RATE' : 30,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801','RATE_NAME' : '100000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801','RATE_NAME' : '200000','RATE' : 70,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801','RATE_NAME' : '300000','RATE' : 85,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801','RATE_NAME' : '400000','RATE' : 100,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801','RATE_NAME' : '500000','RATE' : 105,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801E','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801E','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801E','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801E','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801E','RATE_NAME' : '50000','RATE' : 30,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801E','RATE_NAME' : '100000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801E','RATE_NAME' : '200000','RATE' : 70,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801E','RATE_NAME' : '300000','RATE' : 85,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801E','RATE_NAME' : '400000','RATE' : 100,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801E','RATE_NAME' : '500000','RATE' : 105,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '801E','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802','RATE_NAME' : '50000','RATE' : 12,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802','RATE_NAME' : '100000','RATE' : 19,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802','RATE_NAME' : '200000','RATE' : 25,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802','RATE_NAME' : '300000','RATE' : 28,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802','RATE_NAME' : '400000','RATE' : 29,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802','RATE_NAME' : '500000','RATE' : 30,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802E','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802E','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802E','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802E','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802E','RATE_NAME' : '50000','RATE' : 12,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802E','RATE_NAME' : '100000','RATE' : 19,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802E','RATE_NAME' : '200000','RATE' : 25,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802E','RATE_NAME' : '300000','RATE' : 28,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802E','RATE_NAME' : '400000','RATE' : 29,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802E','RATE_NAME' : '500000','RATE' : 30,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '802E','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803','RATE_NAME' : '50000','RATE' : 30,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803','RATE_NAME' : '100000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803','RATE_NAME' : '200000','RATE' : 70,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803','RATE_NAME' : '300000','RATE' : 85,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803','RATE_NAME' : '400000','RATE' : 100,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803','RATE_NAME' : '500000','RATE' : 105,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803E','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803E','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803E','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803E','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803E','RATE_NAME' : '50000','RATE' : 30,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803E','RATE_NAME' : '100000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803E','RATE_NAME' : '200000','RATE' : 70,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803E','RATE_NAME' : '300000','RATE' : 85,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803E','RATE_NAME' : '400000','RATE' : 100,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803E','RATE_NAME' : '500000','RATE' : 105,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '803E','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804','RATE_NAME' : '50000','RATE' : 30,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804','RATE_NAME' : '100000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804','RATE_NAME' : '200000','RATE' : 70,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804','RATE_NAME' : '300000','RATE' : 85,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804','RATE_NAME' : '400000','RATE' : 100,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804','RATE_NAME' : '500000','RATE' : 105,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804E','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804E','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804E','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804E','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804E','RATE_NAME' : '50000','RATE' : 30,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804E','RATE_NAME' : '100000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804E','RATE_NAME' : '200000','RATE' : 70,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804E','RATE_NAME' : '300000','RATE' : 85,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804E','RATE_NAME' : '400000','RATE' : 100,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804E','RATE_NAME' : '500000','RATE' : 105,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '804E','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805','RATE_NAME' : '50000','RATE' : 30,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805','RATE_NAME' : '100000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805','RATE_NAME' : '200000','RATE' : 70,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805','RATE_NAME' : '300000','RATE' : 85,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805','RATE_NAME' : '400000','RATE' : 100,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805','RATE_NAME' : '500000','RATE' : 105,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805E','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805E','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805E','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805E','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805E','RATE_NAME' : '50000','RATE' : 30,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805E','RATE_NAME' : '100000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805E','RATE_NAME' : '200000','RATE' : 70,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805E','RATE_NAME' : '300000','RATE' : 85,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805E','RATE_NAME' : '400000','RATE' : 100,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805E','RATE_NAME' : '500000','RATE' : 105,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : '805E','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E11','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E11','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E11','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E11','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E11','RATE_NAME' : '50000','RATE' : 12,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E11','RATE_NAME' : '100000','RATE' : 19,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E11','RATE_NAME' : '200000','RATE' : 25,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E11','RATE_NAME' : '300000','RATE' : 28,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E11','RATE_NAME' : '400000','RATE' : 29,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E11','RATE_NAME' : '500000','RATE' : 30,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E11','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E12','RATE_NAME' : 'Driver','RATE' : 0.003,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E12','RATE_NAME' : 'Passanger','RATE' : 0.0015,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E12','RATE_NAME' : 'Driver Compensate','RATE' : 0.5,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E12','RATE_NAME' : 'Passanger Compensate','RATE' : 0.3,'RATE_CRITERIA' : 'RY01'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E12','RATE_NAME' : '50000','RATE' : 50,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E12','RATE_NAME' : '100000','RATE' : 90,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E12','RATE_NAME' : '200000','RATE' : 110,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E12','RATE_NAME' : '300000','RATE' : 120,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E12','RATE_NAME' : '400000','RATE' : 130,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E12','RATE_NAME' : '500000','RATE' : 135,'RATE_CRITERIA' : 'RY02'},
{'Tariff_type' : 'ADDITIONAL COV','Motor_code_group' : 'E12','RATE_NAME' : '','RATE' : 0.005,'RATE_CRITERIA' : 'RY03'}]